export const TT = {
    zoneCenter: 'resources/40/cell_center.png',
    zoneSide: 'resources/40/cell_up.png',
    stoneV: 'resources/40/stone_violet.png',
    stoneR: 'resources/40/stone_red.png',
    stoneI: 'resources/40/stone_indigo.png',
    stoneO: 'resources/40/stone_orange.png',
    cell: 'resources/40/scheme_cell.png',
    roadL: 'resources/40/road_left.png',
    roadR: 'resources/40/road_right.png',
    roadH: 'resources/40/road_heavy.png',
    roadSleep: 'resources/40/road_sleep.png',
    roadSleepCharge: 'resources/40/road_sleep_charge.png',
    roadSleepFlow: 'resources/40/road_sleep_flow.png',
    roadAwakening: 'resources/40/road_awakening.png',
    roadAwakeningCharge: 'resources/40/road_awake_charge.png',
    roadAwakeningFlow: 'resources/40/road_awake_flow.png',
} as const;